require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/booking_types', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # BookingType. As you add validations to BookingType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BookingType.create! valid_attributes
      get booking_types_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      booking_type = BookingType.create! valid_attributes
      get booking_type_url(booking_type)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_booking_type_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      booking_type = BookingType.create! valid_attributes
      get edit_booking_type_url(booking_type)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BookingType' do
        expect do
          post booking_types_url, params: { booking_type: valid_attributes }
        end.to change(BookingType, :count).by(1)
      end

      it 'redirects to the created booking_type' do
        post booking_types_url, params: { booking_type: valid_attributes }
        expect(response).to redirect_to(booking_type_url(BookingType.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BookingType' do
        expect do
          post booking_types_url, params: { booking_type: invalid_attributes }
        end.to change(BookingType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post booking_types_url, params: { booking_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested booking_type' do
        booking_type = BookingType.create! valid_attributes
        patch booking_type_url(booking_type), params: { booking_type: new_attributes }
        booking_type.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the booking_type' do
        booking_type = BookingType.create! valid_attributes
        patch booking_type_url(booking_type), params: { booking_type: new_attributes }
        booking_type.reload
        expect(response).to redirect_to(booking_type_url(booking_type))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        booking_type = BookingType.create! valid_attributes
        patch booking_type_url(booking_type), params: { booking_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested booking_type' do
      booking_type = BookingType.create! valid_attributes
      expect do
        delete booking_type_url(booking_type)
      end.to change(BookingType, :count).by(-1)
    end

    it 'redirects to the booking_types list' do
      booking_type = BookingType.create! valid_attributes
      delete booking_type_url(booking_type)
      expect(response).to redirect_to(booking_types_url)
    end
  end
end
